# Generated by Django 3.0.5 on 2022-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LDAPServerAddress', models.CharField(max_length=200)),
                ('LDAPUserDirectory', models.CharField(max_length=500)),
            ],
        ),
    ]
