# Generated by Django 3.1.3 on 2022-04-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formSubmission', '0001_initial'),
        ('patientRequirements', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprotocolsequenceconnector',
            name='sequenceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocols.sequence'),
        ),
        migrations.AddField(
            model_name='scheduleprotocolprotocolconnector',
            name='ProtocolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocols.protocol'),
        ),
        migrations.AddField(
            model_name='scheduleprotocolprotocolconnector',
            name='ScheduleProtocolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formSubmission.scheduleprotocol'),
        ),
        migrations.AddField(
            model_name='scheduleprotocol',
            name='customRequisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='formSubmission.customrequisition'),
        ),
        migrations.AddField(
            model_name='customrequisition',
            name='anatomicalLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocols.type'),
        ),
        migrations.AddField(
            model_name='customrequisition',
            name='isolationPrecaution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patientRequirements.isolationprecaution'),
        ),
        migrations.AddField(
            model_name='customrequisition',
            name='mobilityRequirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patientRequirements.mobilityrequirement'),
        ),
        migrations.AddField(
            model_name='customrequisition',
            name='sedationRequirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patientRequirements.sedationrequirement'),
        ),
        migrations.AddField(
            model_name='customrequisition',
            name='subLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocols.typesubpart'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='scheduleProtocol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formSubmission.scheduleprotocol'),
        ),
    ]
