# Generated by Django 3.1.3 on 2022-04-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationPrecaution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolationPrecaution', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilityRequirement', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecautionRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precaution', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SedationRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sedationRequirement', models.CharField(max_length=200, unique=True)),
                ('message', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='IsolationRequirementConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precautionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRequirements.isolationprecaution')),
                ('requirementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRequirements.precautionrequirement')),
            ],
        ),
    ]
