# Generated by Django 3.0.5 on 2022-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationAndAuthentication', 'admin_user_initial(DoNotDelete)'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainuser',
            name='department',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='rainuser',
            name='password',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='rainuser',
            name='site',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='rainuser',
            name='username',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
