# Generated by Django 3.1.3 on 2022-04-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocols.type'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('keyword', 'points', 'type')},
        ),
    ]
