export const Database = [
  {
    strFormName: "MRI Reuqisition Form Template",
    intModality: 0,
    boolEnabled: true,
    intMode: 0,
    arrFields: [
      {
        strFieldName: "Outpatient",
        strFieldValue: "",
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Outpatient", "Preferred Site - Specify"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "EDOutpatientFollowUpWith",
        strFieldValue: [
          { "Time order placed:": false },
          { "ED Physician": false },
          { "Primary Care Provider": false },
        ],
        strFieldAdditionalText: "",
        strFieldValueFormatted: ["", "", ""],
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: [
          "Time order placed",
          "Time order placed - text box",
          "ED physician",
          "Primary care provider",
        ],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "EDOutpatientFollowUpWith_PatientContact",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient contact #"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "EDOutpatientFollowUpWith_PatientName",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient name"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "InpatientED",
        strFieldValue: [
          { Inpatient: false },
          { Site: "" },
          { "Ward / Room #": "" },
          { "EMS Transport": false },
        ],
        strFieldValueFormatted: ["", "", "", ""],
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Inpatient/ED", "Site", "Ward/room #", "EMS transport"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_LastNameFirstName",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient info - last name / first name"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_DOB",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient info - DOB"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_Age",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient info - age"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_Sex",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Sex"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_MHSC",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient info - MHSC"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_PHIN",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient info - PHIN"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_OtherInsuranceWCB",
        strFieldValue: "",
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Other insurance", "Patient info - WCB#"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_FullAddress",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Patient info - full address"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_EmailAddress",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["email address"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_DaytimeMobile",
        strFieldValue: [{ Daytime: "" }, { Mobile: "" }],
        strFieldValueFormatted: ["", ""],
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["phone mobile", "phone daytime"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_EmergencyContactNextOfKin",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["emergency contact / next of kin"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PatientInformation_Translator",
        strFieldValue: false,
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Translator", "Language required"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "Scheduling_Urgency",
        strFieldValue: "",
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Urgency", "Requested Date"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "Scheduling_Transport",
        strFieldValue: [
          { Ambulatory: false },
          { Wheelchair: false },
          { "Bed/Stretcher": false },
          { "Lift Required": false },
        ],
        strFieldValueFormatted: ["", "", "", ""],
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: [
          "Transport - ambulatory",
          "Transport - wheelchair",
          "Transport - bed/stretcher",
          "lift required",
        ],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "Pregnant",
        strFieldValue: "",
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Pregnant", "LMP"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "Claustrophobia",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Claustrophobia"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "RequiresSedation",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Requires sedation"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "InfectionControlPrecautions",
        strFieldValue: "",
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: [
          "Infection control precautions?",
          "Infection control - specify",
        ],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ExamInformation_Weight",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Weight"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ExamInformation_Height",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Height"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ExamInformation_AllergiesRelatedToImaging",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Allergies"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ExamInformation_PediatricPatients",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Pediatric head circumference percentile"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ExamInformation_AnatomicalLocationExaminationRequested",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Anatomical location / examination requested"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ExamInformation_PreviousRelevantExams",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Previous relevant exams"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "RelevantClinicalSurgicalHistory",
        strFieldValue: [
          { "Cancer Care Pathway": false },
          { "Previous Back Surgery": false },
          { relevantClinicalSurgicalHistory: "" },
        ],
        strFieldValueFormatted: ["", "", ""],
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: [
          "Cancer Care Pathway",
          "Previous back surgery",
          "Relevant Clinical / Surgical History",
        ],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "ForIVContrastExams",
        strFieldValue: "",
        strFieldValue2: "",
        strFieldAdditionalText: ["", "", "", ""],
        strFieldValueFormatted: ["", "", "", ""],
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Renal disease", "SCr", "eGFR", "Renal - date"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_PacemakerDefibrillator",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Pacemaker?"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_DrugInfusionPump",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Drug infusion pump / glucose monitoring device"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_NeuroOrSpinalCordStimulator",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Neuro or spinal cord?"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_SurgicalImplants",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Surgical implants"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_LoopRecorder",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Loop recorder"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName:
          "PreAppointmentScreening_WelderWorkWithMetalAnyMetalInEyes",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Welder / works with metal / any metal in eyes?"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_STRATAValve",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["STRATA valve"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName:
          "PreAppointmentScreening_BulletShrapnelOrOtherMetalForeignBody",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Bullet / shrapnel or other metal foreign body"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_CochlearImplant",
        strFieldValue: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Cochlear implant?"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "PreAppointmentScreening_Other",
        strFieldValue: "",
        strFieldAdditionalText: "",
        strFieldValueFormatted: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Other", "Other - pre-appointment screening"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_ClinicianSignature",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: [""],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_ClinicianName",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Clinician name"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_Billing",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Billing #"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_Fax",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Fax #"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_24hrCriticalResultsContact",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["24 hr"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_Address",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Address"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_Phone",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Phone #"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_DateOrdered",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Date ordered"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_TimeOrdered",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Time ordered (24 hr"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_CopyToClinicianName",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Copy to - clinician name"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_CopyToLocation",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Copy to - location"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_CopyToPhone",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Copy to - phone #"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
      {
        strFieldName: "OrderingClinician_CopyToFax",
        strFieldValue: "",
        boolFieldValidated: false,
        objFieldRules: {
          boolRequired: true,
          boolAttachmentSupported: true,
          boolAttachmentRequired: false,
          boolBypassAllowed: false,
        },
        pdfParserKey: ["Copy to - fax #"],
        pdfParserValue: "",
        pdfParserValueConvertor: "",
      },
    ],
  },
  {
    strFormName: "New Form...",
    intModality: 0,
    boolEnabled: false,
    intMode: 1,
    arrFields: [],
  },
];
